server:
  port: 80
  servlet:
#    context-path: /demo

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?autoReconnect=true&useSSL=false
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

springfox:
  documentation:
    swagger-ui:
      enabled: true
      contact:
        fullname: Songnan Bao
        website: https://github.com/songnanbao/spring-demo
        email: songnan.bao@hotmail.com